name: ffwebapp-ci-cd-argocd

on:
  #push:
  #  branches:
  #    - feature/*
  #    - release/*
  #    - develop
  #pull_request:
  #  branches:
  #    - develop
  #    - main
  workflow_dispatch: 

env:
  RESOURCE_GROUP: "rg_aksgitopspush"
  AZURE_CONTAINER_REGISTRY: "crffwebappdev"
  AZURE_CONTAINER_REGISTRY_URL: "crffwebappdev.azurecr.io"
  CONTAINER_NAME: "ffwebapp"  
  CLUSTER_NAME: "aks-ffwebapp"
  DEPLOYMENT_MANIFEST_PATH: "src/ffwebapp/ffwebapp.yaml"
  
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: ACR Login
        run: az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY_URL }}
      
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: src/ffwebapp
          file: src/ffwebapp/Dockerfile
          tags: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
             ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:latest
          push: true
    
      - name: View images
        run: docker images
  
  modify-config-files:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v4
        name: Checkout config repository
        with:
          repository: 'mrfiliputti/aks-gitops-push'
          token: ${{ secrets.GH_PAT }}
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      
      - name: Modify deployment files
        run: |
          echo "--- Image Label ---"
          echo $IMAGE_LABEL

          echo "--- Set git config ---"
          git config user.email actions@github.com
          git config user.name "GitHub Actions"
          
          echo "--- View directory ---"
          pwd
          
          echo "::group::file"
          echo "--- View webapi image ---"
          cat src/ffwebapp/ffwebapp.yaml | grep "image:" | awk -F'"' '{print $2}'
          
          echo "--- Replace image tag ---"
          sed -i "s|crffwebappdev.azurecr.io/ffwebapp:[^\"]*|crffwebappdev.azurecr.io/ffwebapp:$IMAGE_LABEL|" src/ffwebapp/ffwebapp.yaml
          
          echo "--- View modified image ---"
          cat src/ffwebapp/ffwebapp.yaml | grep "image:" | awk -F'"' '{print $2}'
          echo "::endgroup::"

          echo "::group::Git commands"
          echo "--- Git commit and push ---"
          git status
          git add .
          git commit -m "Done by Github Actions Job changemanifest: $IMAGE_LABEL"
          git push origin main
          echo "::endgroup::"
        env:
          IMAGE_LABEL: ${{ github.sha }}